### PR TITLE
Add a container to run ipr database migrations before starting the api

### PR DESCRIPTION
**Pull request by brayden-bcgsc**

### CODE REVIEW

**Review by mathieulemieux — COMMENTED** [review]
I get the same error as before : https://www.bcgsc.ca/jira/browse/KBDEV-971?focusedCommentId=1579284&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1579284
Logs of ipr_api: [2022-05-13 16:42:27][ERROR] Unable to lookup reports SequelizeDatabaseError: column report.pediatric_ids does not exist

**Comment by brayden-bcgsc** [comment]
@mathieulemieux Can you paste the logs from the 'migrations' container here?

**Comment by mathieulemieux** [comment]
[migration.log](https://github.com/bcgsc/pori/files/8689720/migration.log)

**Comment by mathieulemieux** [comment]
[migration.log](https://github.com/bcgsc/pori/files/8689740/migration.log)
Updated file, sorry

**Comment by mathieulemieux** [comment]
Ok, it is kinda working now BUT I had to nuke the database first otherwise keycloak container was shutting down, so probably not in the spirit of a migration right?

Here is an error found in the keycloak container:
*** JBossAS process (235) received TERM signal ***
User with username 'admin' already added to '/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json'

**Review by mathieulemieux — DISMISSED** [review]
This PR fix the issue with report loading in the IPR client.
Other issues are unrelated.

Here is the migration container log:
Sequelize CLI [Node: 16.15.0, CLI: 6.3.0, ORM: 6.8.0]

Parsed url postgres://ipr_service:*****@ipr_db:5432/ipr_demo
== 20211108213152-DEVSU-1674-add-appendix-to-templates: migrating =======
adding a unique index on the non-deleted record for the table templates_appendix and columns ident
adding a unique index on the non-deleted record for the table templates_appendix and columns template_id
== 20211108213152-DEVSU-1674-add-appendix-to-templates: migrated (0.031s)

== 20211112185802-DEVSU-1657-remove-full-project-access-group-from-database: migrating =======
== 20211112185802-DEVSU-1657-remove-full-project-access-group-from-database: migrated (0.008s)

== 20211214225030-DEVSU-1690-add-support-for-new-exp-density-images: migrating =======
== 20211214225030-DEVSU-1690-add-support-for-new-exp-density-images: migrated (0.008s)

== 20220120192720-DEVSU-1708-split-dbsnp-into-separate-columns: migrating =======
== 20220120192720-DEVSU-1708-split-dbsnp-into-separate-columns: migrated (0.015s)

== 20220125001042-DEVSU-1710-add-support-for-cancer-predisposition: migrating =======
== 20220125001042-DEVSU-1710-add-support-for-cancer-predisposition: migrated (0.005s)

== 20220217221235-DEVSU-1742-get-kbmatches-review-status-during-upload: migrating =======
== 20220217221235-DEVSU-1742-get-kbmatches-review-status-during-upload: migrated (0.006s)

== 20220224185209-DEVSU-1729-add-germline-field-to-all-variant-types: migrating =======
== 20220224185209-DEVSU-1729-add-germline-field-to-all-variant-types: migrated (0.008s)

== 20220314213710-DEVSU-1749-add-new-fields-to-probe-test-information: migrating =======
== 20220314213710-DEVSU-1749-add-new-fields-to-probe-test-information: migrated (0.019s)

== 20220323221350-DEVSU-1763-add-germline-field-to-genomic-alterations-identified: migrating =======
== 20220323221350-DEVSU-1763-add-germline-field-to-genomic-alterations-identified: migrated (0.007s)

== 20220406161001-DEVSU-1130-restrict-deletion-of-users-who-have-signed-a-report: migrating =======
== 20220406161001-DEVSU-1130-restrict-deletion-of-users-who-have-signed-a-report: migrated (0.012s)

== 20220408172355-DEVSU-949-add-unique-constraint-to-genomic-alterations-identified: migrating =======
== 20220408172355-DEVSU-949-add-unique-constraint-to-genomic-alterations-identified: migrated (0.007s)

== 20220422164659-DEVSU-1804-add-support-for-pediatric-ids: migrating =======
== 20220422164659-DEVSU-1804-add-support-for-pediatric-ids: migrated (0.006s)

== 20220425203710-DEVSU-1758-add-library-name-field-to-all-variant-types: migrating =======
== 20220425203710-DEVSU-1758-add-library-name-field-to-all-variant-types: migrated (0.008s)

== 20220503180112-DEVSU-1543-add-description-for-templates: migrating =======
== 20220503180112-DEVSU-1543-add-description-for-templates: migrated (0.005s)

**Comment by creisle** [comment]
This looks good for adding the migration, but it seems like we've got a few other problems to debug before we can release so I've set up a develop branch and changed the target of this PR to that

**Review by creisle — APPROVED** [review]

**Pull request merged**
